### ISSUE TITLE
DB takarítás.

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#75]
Sokkal több probléma van az adatbázisban mint azt elsőre látszott.

- [x] #74 {system}.owner takarítás
- [x] #73 Blog modul és tartalom típus
- [x] #80 munkakozveito tartalom típus törlése
- [x] #81 translator tartalom típus törlése
- [x] #82 issue tartalom típus törlése
- [x] #83 Kikapcsolt modulok uninstall-lálása
- [x] #84 Schema modul javaslatai szerinti takarítás
- [x] #94 Non exists modules in the {system} table

Mivel nagyon egyforma feladatokról van szó, lehet hogy praktikus lenne őket egy hook_update_N()-ben elintézni.
