### ISSUE TITLE
Node type: link

### ISSUE THREAD

**Issue by Sweetchuck** [drupalhu/drupal.hu#85]
A _Webhely ajánlása_ tartalom típussal kapcsolatos tennivalók:
- [ ] #87 Node type: link - vocabulary_7 létjogosultsága
- [ ] #88 Node type: link - upload field
- [ ] #89 Node type: link - Editors choice
- [ ] #90 Node type: link - Drupal version
